name: saucedemo-tests

networks:
  lowmtu:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1420

services:
  api:
    build:
      context: .
      dockerfile: e2e/Dockerfile
    shm_size: 1g
    working_dir: /app
    env_file:
      - .env
    environment:
      CI: 'true'
    dns: [1.1.1.1, 8.8.8.8]
    networks: [lowmtu]
    volumes:
      - ./playwright-report-api:/app/playwright-report
      - ./test-results-api:/app/test-results
    command: >
      sh -lc "npx playwright test -c playwright.api.config.ts"

  e2e:
    build:
      context: .
      dockerfile: e2e/Dockerfile
    shm_size: 1g
    working_dir: /app
    env_file:
      - .env
    environment:
      CI: 'true'
    dns: [1.1.1.1, 8.8.8.8]
    networks: [lowmtu]
    volumes:
      - ./playwright-report-e2e:/app/playwright-report
      - ./test-results-e2e:/app/test-results
    command: >
      sh -lc "
        npx bddgen &&
        if [ -n \"$GREP\" ]; then
          npx playwright test --grep \"$GREP\";
        else
          npx playwright test;
        fi
      "
  k6-all:
    image: grafana/k6:latest
    working_dir: /scripts
    env_file:
      - .env
    environment:
      K6_TEST: all
    dns: [1.1.1.1, 8.8.8.8]
    networks: [lowmtu]
    volumes:
      - ./k6:/scripts
    entrypoint: ['/bin/sh', '/scripts/run.sh']
